# HW5: Image Captioning
---

This is the Notebook that goes with **Homework 5: Image Captioning**! 

In this notebook, you can run the assignments main method and train either the RNN or the Transformer model, instead of running the assignment on your personal machine. In addition, you can visualize the self-attention layer in your TransformerDecoder, and generate captions using both of your models for images in the test dataset. 

This notebook can be ported to Colab very quickly, so please feel free to try that out! It might also make some of the training quicker...

## Preparation Code

If need be, feel free to pull your content from GitHub using this or a similar cell of choice. This should be moderately standard-practice for some of you. Additionally, remember to %cd to the required directories as needed for your workflow!

In [9]:
# #@title Github Clone A Repository
# #@markdown **NOTE**: Must use access token as password. To make one, go [here](https://github.com/settings/tokens) and save your token!

# from IPython.display import clear_output
# import sys, os

# git_user_default = 'your-github-username'
# git_user = 'your-github-username'  #@param {type:"string"}
# if git_user == git_user_default:
#   git_user = input("Enter your Github username: ")
# parent_repo = 'Brown-Deep-Learning'
# assignment_name = 'homework5_imagecaption'  #@param {type:"string"}
# github_repo = f'{parent_repo}/{assignment_name}-{git_user}'
# force_reclone = True           #@param {type:"boolean"}
# is_private_repo = True            #@param {type:"boolean"}
# keep_gh_login = True            #@param {type:"boolean"}

# user_dir, github_dir = github_repo.split('/')
# data_file = f'{github_dir}/hw5/data/data.p'

# if not os.path.isdir(github_dir) or force_reclone:
    
#     if is_private_repo:
#         if 'git_user' not in globals() or 'git_pass' not in globals():
#             # git_user = input("Username: ")
#             git_pass = input("GH Token: ")
#             clear_output() 

#     if force_reclone:
#         !rm -rf {github_dir} &> /dev/null

#     if is_private_repo:
#         !git clone https://{git_user}:{git_pass}@github.com/{github_repo}.git
#         if not keep_gh_login:
#             del git_user, git_pass 
#     else: 
#         !git clone https://github.com/{github_repo}.git

This block of code imports the classes you completed in your assignment, along with additional libraries needed for the visualizations.

Feel free to add autoimport queries as needed. This notebook's code will not be auto-ran by the autograder (only the outputs will be looked at during manual grading), so do what you need to here. 

In [10]:
import sys
import numpy as np
import matplotlib.pyplot as plt
import pickle

from model import ImageCaptionModel
from decoder import TransformerDecoder, RNNDecoder

## Exploring the Dataset

This assignment uses the Flickr 8k dataset! Let's go ahead and pull that in!

In [11]:
## Before this, download the dataset and run preprocessing.py as instructed. 
## This may take like 10 mins, but should only happen once so ok.
## https://www.kaggle.com/datasets/adityajn105/flickr8k?resource=download

with open('../data/data.p', 'rb') as data_file:
    data_dict = pickle.load(data_file)

# As mentioned in the handout, this assignment has 5 captions per image. This block of code 
# expands the image_feature lists to have 5 copies of each image to correspond to each of their captions 
feat_prep = lambda x: np.repeat(np.array(x).reshape(-1, 2048), 5, axis=0)
img_prep  = lambda x: np.repeat(x, 5, axis=0)

## Captions; preprocessed sentences with 20 window size
train_captions  = np.array(data_dict['train_captions']);            print('train_captions:  ', train_captions.shape)
test_captions   = np.array(data_dict['test_captions']);             print('test_captions:   ', test_captions.shape)

## 2048-D resnet embeddings of images.
train_img_feats = feat_prep(data_dict['train_image_features']);     print('\ntrain_img_feats: ', train_img_feats.shape)
test_img_feats  = feat_prep(data_dict['test_image_features']);      print('test_img_feats:  ', test_img_feats.shape)

## Small subset of actual images for visualization purposes. 
## These are just for the first 100 images of each (clones 5 times)
train_images    = img_prep(data_dict['train_images']);              print('\ntrain_images:    ', train_images.shape)
test_images     = img_prep(data_dict['test_images']);               print('test_images:     ', test_images.shape)

## Conversion dictionaries to go between word and label index
word2idx        = data_dict['word2idx']
idx2word        = data_dict['idx2word']

train_captions:   (35455, 21)
test_captions:    (5000, 21)

train_img_feats:  (35455, 2048)
test_img_feats:   (5000, 2048)

train_images:     (500, 224, 224, 3)
test_images:      (500, 224, 224, 3)


Since the images take up a lot of data, we only kept a sliver of the original images. Feel free to update the preprocessing to retain all of the images if you'd like. Below is a visualization of some of the data:

In [ ]:
for i in range(5):
    for j in range(5):
        print(f'Caption {j+1}:', ' '.join([idx2word[idx] for idx in train_captions[i * 5 + j]]))
    plt.imshow(train_images[i * 5])
    plt.show()

## Training your model

As always you can complete and run this assignments main method on your personal machine. However, you can also choose to run the assignment in this notebook to take advantage of Colab's GPU allocation! 

### Running your RNN model

Depending on your use cases, you may choose to structure your model in a variety of ways. In contrast to previous assignments, this one is intended to mimic a lot of modern research-oriented repositories you might find in the wild. Specifically: **Instead of providing easy-to-use APIs for experimenters, they rigidify their implementation to make tests replicable.** Specifically, they may provide a command-line interface and define testing/training procedures which log results. 

(I mean, ideally you can make a flexible API and allow for both ease of extension and examples to demonstrate how your results were gathered, but sometimes researchers only have so much time...)

Once you have filled in the `model.py` components and the `RNNDecoder` of the `decoder.py` file, run this block to train your RNN model. As you can see, the hyperparamets default to the ones you use in `assignment.py`'s argparse specification, but feel free to change any of them to try to improve your model. 




You can investigate `assignment.py` to find that main will try to parse command-line arguments and fill in a variety of defaults. Specifically, you'll find this: 
```python
def parse_args(args=None):
    """ 
    Perform command-line argument parsing (other otherwise parse arguments with defaults). 
    To parse in an interative context (i.e. in notebook), add required arguments.
    These will go into args and will generate a list that can be passed in.
    For example: 
        parse_args('--type', 'rnn', ...)
    """
    parser = argparse.ArgumentParser(...)
    parser.add_argument('--type',           required=True,              ...)
    parser.add_argument('--task',           required=True,              ...)
    parser.add_argument('--data',           required=True,              ...')
    parser.add_argument('--epochs',         type=int,   default=3,      ...)
    parser.add_argument('--lr',             type=float, default=1e-3,   ...)
    parser.add_argument('--optimizer',      type=str,   default='adam', ...)
    parser.add_argument('--batch_size',     type=int,   default=100,    ...)
    parser.add_argument('--hidden_size',    type=int,   default=256,    ...)
    parser.add_argument('--window_size',    type=int,   default=20,     ...)
    parser.add_argument('--chkpt_path',     default='',                 ...)
    parser.add_argument('--check_valid',    default=True,               ...)
    if args is None: 
        return parser.parse_args()      ## For calling through command line
    return parser.parse_args(args)      ## For calling through notebook.
```

When trying to run the file by default, you'll get a nice usage error message if you are missing any required arguments:

In [39]:
!python assignment.py

usage: assignment.py [-h] --type {rnn,transformer} --task {train,test,both}
                     --data DATA [--epochs EPOCHS] [--lr LR]
                     [--optimizer {adam,rmsprop,sgd}]
                     [--batch_size BATCH_SIZE] [--hidden_size HIDDEN_SIZE]
                     [--window_size WINDOW_SIZE] [--chkpt_path CHKPT_PATH]
                     [--check_valid]
assignment.py: error: the following arguments are required: --type, --task, --data


This shows what kinds of arguments can be passed into your python file via main, and is reminiscent of what you might have seen in HW3. 

The following command will therefore be sufficient to try what an author (or you) might consider to be a "default training run" of the model: 

In [41]:
## TODO: Increase epochs to a larger size when ready (maybe 2 or 3 would be enough?)
!python assignment.py --type rnn --task train --data ../data/data.p --epochs 4 --chkpt_path ../rnn_model
## if using colab, you may need to do something like the following or might need to %cd into the directory of interest first...

[Valid 354/354]	 loss=3.763	 acc: 0.240	 perp: 43.082[[ 13  50  52 ...  16  16  16]
 [ 13 167  44 ...  16  16  16]
 [186 415  65 ...  16  16  16]
 ...
 [217 119 120 ...  16  16  16]
 [214 147   2 ...  16  16  16]
 [ 22 190 249 ...  16  16  16]]
[Valid 1/50]	 loss=3.407	 acc: 0.274	 perp: 30.185[[214   2  92 ...  72  15  16]
 [ 17  79   2 ...  16  16  16]
 [ 17  79 157 ...  16  16  16]
 ...
 [  1   2  86 ...  16  16  16]
 [ 97   1   2 ...  16  16  16]
 [180   1  44 ...  16  16  16]]
[Valid 2/50]	 loss=3.315	 acc: 0.279	 perp: 27.535[[ 86   1  44 ...  16  16  16]
 [  1   2  68 ...  16  16  16]
 [  1  11 461 ...  16  16  16]
 ...
 [462 421 558 ...  16  16  16]
 [ 13 307  44 ...  16  16  16]
 [462   2   3 ...  16  16  16]]
[Valid 3/50]	 loss=3.277	 acc: 0.289	 perp: 26.489[[ 66  34 408 ...  16  16  16]
 [ 34  69   3 ...  16  16  16]
 [319 240  34 ...  16  16  16]
 ...
 [ 34   6  32 ...  16  16  16]
 [ 34 318   3 ...  16  16  16]
 [ 34  32  17 ...  16  16  16]]
[Valid 4/50]	 loss=3.276	 acc

Since this command also saves the model, we should be able to load it back in and use it. Feel free to modify the saving utility as needed based on your modifications, but the default system should work fine for the initial requirements. 

In [42]:
!python assignment.py --type rnn --task test --data ../data/data.p --chkpt_path ../rnn_model

Model loaded from '../rnn_model'
[[ 13  50  52 ...  16  16  16]
 [ 13 167  44 ...  16  16  16]
 [186 415  65 ...  16  16  16]
 ...
 [217 119 120 ...  16  16  16]
 [214 147   2 ...  16  16  16]
 [ 22 190 249 ...  16  16  16]]
[Valid 1/50]	 loss=3.129	 acc: 0.313	 perp: 22.857[[214   2  92 ...  72  15  16]
 [ 17  79   2 ...  16  16  16]
 [ 17  79 157 ...  16  16  16]
 ...
 [  1   2  86 ...  16  16  16]
 [ 97   1   2 ...  16  16  16]
 [180   1  44 ...  16  16  16]]
[Valid 2/50]	 loss=3.001	 acc: 0.323	 perp: 20.105[[ 86   1  44 ...  16  16  16]
 [  1   2  68 ...  16  16  16]
 [  1  11 461 ...  16  16  16]
 ...
 [462 421 558 ...  16  16  16]
 [ 13 307  44 ...  16  16  16]
 [462   2   3 ...  16  16  16]]
[Valid 3/50]	 loss=2.979	 acc: 0.333	 perp: 19.659[[ 66  34 408 ...  16  16  16]
 [ 34  69   3 ...  16  16  16]
 [319 240  34 ...  16  16  16]
 ...
 [ 34   6  32 ...  16  16  16]
 [ 34 318   3 ...  16  16  16]
 [ 34  32  17 ...  16  16  16]]
[Valid 4/50]	 loss=2.944	 acc: 0.332	 perp: 18.98

### Running your Transformer model

Once you have completed the `transformer.py` file, run this block to train your transformer based model. Note that running with the `both` task will both train, save, and test your model in one go.

In [16]:
## TODO: Increase epochs to a larger size when ready (maybe 2 or 3 would be enough?)
!python assignment.py --type transformer --task both --data ../data/data.p --epochs 4 --lr 0.0005 --chkpt_path ../transform_model

Traceback (most recent call last):
  File "/Users/noracai/Documents/CS1470/homework-5p-image-captioning-norafk/code/assignment.py", line 171, in <module>
    main(parse_args())
  File "/Users/noracai/Documents/CS1470/homework-5p-image-captioning-norafk/code/assignment.py", line 76, in main
    train_model(
  File "/Users/noracai/Documents/CS1470/homework-5p-image-captioning-norafk/code/assignment.py", line 149, in train_model
    stats += [model.train(captions, img_feats, pad_idx, batch_size=args.batch_size)]
  File "/Users/noracai/Documents/CS1470/homework-5p-image-captioning-norafk/code/model.py", line 59, in train
    loss = self.loss_function(probs, decoder_labels, mask)
  File "/Users/noracai/Documents/CS1470/homework-5p-image-captioning-norafk/code/model.py", line 181, in loss_function
    masked_prbs = tf.boolean_mask(prbs, mask)
  File "/Users/noracai/anaconda3/envs/csci1470/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    

You should be able to reach validation perplexity in the ballpark of 15-18 by the end of training! We found that around 4 epochs was enough for our settings, but your results may vary. Though you are not constrained by any time limits, know when to stop and try to be proactive with your time. 

## Visualization

After training our Transformer model, you can visualize the self-attention layer to examine the behavior of your attention heads and see if any patterns emerge. 

To test out the components of the model interactively, you'll need to deconstruct selections of the model/runner code and get an instance of the model in an interactive context (aka inside the notebook). 



In [17]:
## Feel free to insert auto-reloads as necessary
from assignment import parse_args, load_model
from decoder import TransformerDecoder, RNNDecoder

## Pull your model into the notebook. This is heavily based off of assignment.py, 
## and feel free to reuse as much as you want. Your final project will probably 
## involve a lot of this investigative reverse-engineering based on what repos 
## you have to stumble upon.
## You're not in a notebook scenario, so use get_default_arguments and feel free to update it...

args = parse_args('--type rnn --task both --data ../data/data.p'.split())

args.chkpt_path = '../transform_model'
tra_imcap = load_model(args)

args.chkpt_path = '../rnn_model'
rnn_imcap = load_model(args)

OSError: No file or directory found at ../transform_model

In [ ]:
rnn_imcap.summary()

In [ ]:
tra_imcap.summary()

Now that we have our model, we need to be able to actually access the attention matrix that gets generated by out model. So that we can visualize it, right? Unfortunately for us, some convenience methods that allow you to make arbitrary model slices (i.e. the Functional API) are forfeit since our model is a subclass (in contrast to a sequential or functional). 

However, we can still dig into the model and force out way to computing the components we want. Our weights have been saved, after all...

The following block of code visualizes the decoder self-attention for a random images in the test dataset. 


Move your mouse over the words in the left hand column, and see how much attention your decoder self-attention layer pays to each word in the sentance as it encodes each word.

In [ ]:
import tensorflow as tf
from vis_utils import plot_decoder_text_attention
import numpy as np

index = np.random.choice(np.array(list(range(0,500,5))))

caption    = test_captions[index][:-1]
image_feat = test_img_feats[index]
image      = test_images[index]

print("Image number:", index)

def get_attention(tra_imcap, image_feat, caption):
    ## TODO: If you're implementing multi-headed attension, you may need to change 
    ## some stuff to display to display all of the attention matrices.

    ## Into impac decoder (NOTE: expand_dims only necessary for Transformer)
    encoded_images = tra_imcap.decoder.image_embedding(tf.expand_dims(image_feat, 1))
    # captions = tra_imcap.decoder.embedding(caption)
    captions = tra_imcap.decoder.encoding(caption)
    ## Into imcap TransformerBlock; get self-attention
    AttentionHead = tra_imcap.decoder.decoder.self_atten
    K = tf.tensordot(captions, AttentionHead.K, 1)
    V = tf.tensordot(captions, AttentionHead.V, 1)
    self_atten = AttentionHead.attn_mtx((K, V))
    ## Into imcap TransformerBlock; get context self-attention
    AttentionHead = tra_imcap.decoder.decoder.self_context_atten
    K = tf.tensordot(captions, AttentionHead.K, 1)
    V = tf.tensordot(captions, AttentionHead.V, 1)
    self_context_atten = AttentionHead.attn_mtx((K, V))
    return self_atten, self_context_atten


def vis_attention(atten_mtx, image_features, caption, idx2word):
    caption_words = [idx2word[idx] for idx in caption]
    end_sentance_index = caption_words.index('<end>') if '<end>' in caption_words else 20
    caption_words = caption_words[:end_sentance_index]
    AttentionMatrix = atten_mtx[:, :end_sentance_index, :end_sentance_index]
    AttentionMatrix = tf.reshape(AttentionMatrix, (1, 1, 1, end_sentance_index, end_sentance_index))
    plot_decoder_text_attention(attention=AttentionMatrix, tokens=caption_words)

self_atten, self_context_atten = get_attention(
    tra_imcap, tf.expand_dims(image_feat, 0), tf.expand_dims(caption, 0)
)

print("self_atten")
vis_attention(self_atten, image_feat, caption, idx2word)

print("self_context_atten")
vis_attention(self_context_atten, image_feat, caption, idx2word)

plt.imshow(image)
plt.show()

### Caption Generation
Now that you have trained both of your models, it's time to use them to generate original captions for images in the testing set. First, the model is given the <start\> token and asked to generate probabilites for the next word in the sequence. The next token is chosen by sampling from that probability. This process repeats until the model generates the <end\> token, or the maximum sequence length is reached.

 



There is still one piece of this equation missing. The tokens are sampled from the probabilities your models generate, but your models were required to output logits, not probabilities. This is becasue this assignment, like many NLP models, uses temperature as a parameter in text generation. If the models sampled from  probabilies calculated by simply applying softmax to the logits, then the probability of the most likely word will usually be very high and the models will usually genrate the same, most probable caption every time. We use the temperature as a parameter to even out the probabilites so the model produces more 'creative' captions. This is done by dividing the logits by the temperature parameter before applying softmax. Higher temprature values will give a more creative captiong, while temprature values closer to 0 will be more greedy. Check out [this](https://lukesalamone.github.io/posts/what-is-temperature/) article for a demonstration and further explaination of temprature in NLP models.


The following blocks of code will generate a caption for the image currently selected for the attention visualization above. Try playing around with different temperature values and see how it changes the captions your models generate

In [ ]:
def gen_caption_temperature(model, image_embedding, wordToIds, padID, temp, window_length):
    """
    Function used to generate a caption using an ImageCaptionModel given
    an image embedding. 
    """
    idsToWords = {id: word for word, id in wordToIds.items()}
    unk_token = wordToIds['<unk>']
    caption_so_far = [wordToIds['<start>']]
    while len(caption_so_far) < window_length and caption_so_far[-1] != wordToIds['<end>']:
        caption_input = np.array([caption_so_far + ((window_length - len(caption_so_far)) * [padID])])
        logits = model(np.expand_dims(image_embedding, 0), caption_input)
        logits = logits[0][len(caption_so_far) - 1]
        probs = tf.nn.softmax(logits / temp).numpy()
        next_token = unk_token
        attempts = 0
        while next_token == unk_token and attempts < 5:
            next_token = np.random.choice(len(probs), p=probs)
            attempts += 1
        caption_so_far.append(next_token)
    return ' '.join([idsToWords[x] for x in caption_so_far][1:-1])

temperature = .05
gen_caption_temperature(tra_imcap, image_feat, word2idx, word2idx['<pad>'], temperature, args.window_size)


In [ ]:
temperature = 0.2
gen_caption_temperature(tra_imcap, image_feat, word2idx, word2idx['<pad>'], temperature, args.window_size)


**NOTE:** You may want to try a different image. Sometimes you get really unlucky with random selection.

## Generating Sentences for Training Data 

In [ ]:
temperature = 0.05
indices = np.random.choice(np.array(list(range(0, 500, 5))), 10, replace=False)
for i in indices:
    curr_image_feat = train_img_feats[i]
    curr_image      = train_images[i]
    for j in range(5):  ## Display all of the captions trained on
        words = [idx2word[x] for x in train_captions[i+j][:-1] if idx2word[x] not in ('<pad>', '<start>', '<end>')]
        print(f'C{j+1}:', ' '.join(words))
    print('RNN:', gen_caption_temperature(rnn_imcap, curr_image_feat, word2idx, word2idx['<pad>'], temperature, args.window_size))
    print('TRA:', gen_caption_temperature(tra_imcap, curr_image_feat, word2idx, word2idx['<pad>'], temperature, args.window_size))
    plt.imshow(curr_image)
    plt.show()

### Trying out on things in testing set!

In [ ]:
temperature = 0.05
indices = np.random.choice(np.array(list(range(0, 500, 5))), 10, replace=False)
for i in indices:
    curr_image_feat = test_img_feats[i]
    curr_image      = test_images[i]
    for j in range(5):  ## Display all of the captions trained on
        words = [idx2word[x] for x in test_captions[i+j][:-1] if idx2word[x] not in ('<pad>', '<start>', '<end>')]
        print(f'C{j+1}:', ' '.join(words))
    print('RNN:', gen_caption_temperature(rnn_imcap, curr_image_feat, word2idx, word2idx['<pad>'], temperature, args.window_size))
    print('TRA:', gen_caption_temperature(tra_imcap, curr_image_feat, word2idx, word2idx['<pad>'], temperature, args.window_size))
    plt.imshow(curr_image)
    plt.show()

# Conclusion!
Congrats! You have finished this assignment! Below, put down your favorite captions that your RNN and Transformer models both generated!  

In [ ]:
## TODO: fill in the ? and display the vis images with the generated caption below it

rnn_image_index = 42#?
rnn_caption = gen_caption_temperature(rnn_imcap, test_img_feats[rnn_image_index], word2idx, word2idx['<pad>'], temperature, args.window_size)

tra_image_index = 23#?
tra_caption = gen_caption_temperature(tra_imcap, test_img_feats[tra_image_index], word2idx, word2idx['<pad>'], temperature, args.window_size)

print(rnn_caption)
plt.imshow(test_images[rnn_image_index])
plt.show()

print(tra_caption)
plt.imshow(test_images[tra_image_index])
plt.show()